version: "3.9"

services:
  php:
    image: moodyra/php:8.3-alpine
    depends_on:
      - db
    volumes:
      - .:/var/www
  web:
    image: nginx:1.24-alpine
    environment:
      - TZ=Europe/Paris
    depends_on:
      - php
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432 # On expose le port pour pouvoir inspecter la base pendant la phase de développement
    environment:
      POSTGRES_PASSWORD: bokyo
      POSTGRES_USER: bokyo
      POSTGRES_DB: bokyo
      TZ: Europe/Paris
      PGTZ: Europe/Paris
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
      - ./var:/var/www/var

